export default {
  "homepage":{
    "services_card_title_1":"title",
    "services_card_text_1":"Some quick example text to build on the card title and make up the bulk of the card's content.",
    "services_card_title_2":"title",
    "services_card_text_2":"Some quick example text to build on the card title and make up the bulk of the card's content.",
    "services_card_title_3":"title",
    "services_card_text_3":"Some quick example text to build on the card title and make up the bulk of the card's content.",
    "industries_card_title_1":"INFORMATION TECHNOLOGY",
    "industries_card_text_1":"Information Technology is the most dynamic industry of today with constant transformations, growth, mergers and acquisi- tions. Our expert team caters to this industry by keeping in mind the constantly changing dynam- ics of the companies operating in this vertical....",
    "industries_card_title_2":"REAL ESTATE ENGINEERING & CONSTRUCTION",
    "industries_card_text_2":"Engineering and construction companies have a need for on-going audits to ascertain all aspects of internal operations meet the standards set by the statutory bodies. We understand this and have dedicated re- sources catering to the needs of this industry...",
    "industries_card_title_3":"MANUFATURING",
    "industries_card_text_3":"We undertake financial manage- ment for business operating in diverse industries. Our goal is to provide effective solutions that enable our clients to to accom- plish their objectives...",
    "industries_card_title_4":"RETAIL",
    "industries_card_text_4":"Retail industry has gone through enormous changes after E-Com- merce disrupted the industry as a whole, which enabled as to in- troduce better ERP system with our clients which results in better accounting system, financial and tax planning and better management of cash flow",
    "about_us": "ABOUT US",
    "about_us_title": "A little history",
    "about_us_text1": "We expect the shipment of a limited quantity of green beans next Monday. We’ll be offering the roasted beans from Tuesday, but quantities are limited, so be quick.",
    "about_us_text2": "A little history is the highest mountain in Jamaica and one of the highest peaks in the Caribbean at 7,402 ft. It is the home of",
    "about_us_text3": "Blue Mountain Peak is the highest mountain in Jamaica and one of the highest peaks in the Caribbean at 7,402 ft. It is the home of Blue Mountain coffee and their famous tours. It is located on the border of the Portland and Saint Thomas parishes of Jamaica.",
    "insights_header": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a"
  },
  "aboutpage":{
    "testimonials": "Testimonials",
    "testimonials_text": "Thanks to the team’s impeccable business acumen, the firm has been able to capture a niche market in India and overseas.",
    "overview": "OVERVIEW",
    "overview_text_1": "Roshan Mansoor & Co is a chartered accountancy firm delivering integrated consulting services across auditing, financial services, company legal matters, import & export and taxes. Headquartered in the Indian city of Bengaluru, Roshan & Mansoor is powered by a strong team of chartered accountants who have been placed at leading firms including PricewaterhouseCoopers, ING Group and Goldman Sachs.",
    "overview_text_2": "Thanks to the team’s impeccable business acumen, the firm has been able to capture a niche market in India and overseas.",
    "passionate": "WHAT WE PASSIONATE ABOUT",
    "passionate_text": "As a firm that adheres to all the standard operational norms and practices as specified by ICAI and other statutory bodies, we are driven by the mission of creating an overall busi- ness impact for the clients we work with. As we partner with our clients in their organiza- tional finance planning and audit journey, our ultimate goal is to create make a wholesome difference in their bottom line. Buoyed by the overwhelming response from our clients in India, we have recently gone a step further and added to our portfolio Incorporation ser- vices for setting up business in Singapore and Hong Kong. We have partnered with a lead- ing consulting firm in Singapore to deliver this service.",
    "meet_pillars": "MEET THE PILLARS OF OUR COMPANY",
    "meet_pillars_text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "pillar_1_name": "Roshan Mansoor",
    "pillar_1_title": "Founder and Managing Partner",
    "pillar_2_name": "Prashant Bansal",
    "pillar_2_title": "Has previously worked for E&Y",
    "pillar_3_name": "Shahid Rokadiya",
    "pillar_3_title": "Partner - Hyderabad",
  }
}