export default {
  "homepage": {
    "services_card_title_1": "Assurance",
    "services_card_text_1": "We are committed to serving our clients with the highest possible assurance through our systematic approach.",
    "services_card_title_2": "Tax",
    "services_card_text_2": "We offer end-to-end solutions for all taxation needs from tax planning, documentation to representations. ",
    "services_card_title_3": "Advisory",
    "services_card_text_3": "We provide consultation and advisory services in relation to domestic and international taxation, restructuring and reorganization of companies, acquisitions, and foreign exchange laws.",
    "industries_card_title_1": "Information Technology",
    "industries_card_text_1": "Information Technology is the most dynamic industry of today with constant transformations, growth, mergers and acquisi- tions. Our expert team caters to this industry by keeping in mind the constantly changing dynam- ics of the companies operating in this vertical....",
    "industries_card_title_2": "Real Estate Engineering & Construction",
    "industries_card_text_2": "Engineering and construction companies have a need for on-going audits to ascertain all aspects of internal operations meet the standards set by the statutory bodies. We understand this and have dedicated re- sources catering to the needs of this industry...",
    "industries_card_title_3": "Manufacturing",
    "industries_card_text_3": "We undertake financial manage- ment for business operating in diverse industries. Our goal is to provide effective solutions that enable our clients to to accom- plish their objectives...",
    "industries_card_title_4": "Retail",
    "industries_card_text_4": "Retail industry has gone through enormous changes after E-Com- merce disrupted the industry as a whole, which enabled as to in- troduce better ERP system with our clients which results in better accounting system, financial and tax planning and better management of cash flow",
    "about_us": "ABOUT US",
    "about_us_title": "Roshan Mansoor & Co is a firm of Chartered Accountants in Bangalore, founded by Roshan T Mansoor in the year 2012. The firm delivers integrated consulting services across Auditing, Financial Services, Company Law Matters, Corporate Restructuring, and Taxes. Roshan Mansoor & Co is powered by a strong team of Chartered Accountants who have prior experience with leading firms including PricewaterhouseCoopers, ING Group and Goldman Sachs.",
    "about_us_text1": "Thanks to the team’s impeccable business acumen, the firm has been able to capture a niche market in India and overseas.",
    "about_us_text2": "As a firm that adheres to all the standard operational norms and practices as specified by ICAI and other statutory bodies, we are driven by the mission of creating an overall business impact for the clients we work with. As we partner with our clients in their organizational financial planning and audit journey, our ultimate goal is to make a wholesome difference in their bottom line.",
    "about_us_text3": "Buoyed by the overwhelming response from our clients in India, we have recently gone a step further and added to our portfolio Incorporation services for setting up business and audit services in USA, Singapore and Hong Kong. We have partnered with a leading consulting firm in Singapore to deliver ethese services.`",
    "insights_header": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a"
  },
  "aboutpage": {
    "testimonials": "Testimonials",
    "testimonials_text": "Thanks to the team’s impeccable business acumen, the firm has been able to capture a niche market in India and overseas.",
    "overview": "OVERVIEW",
    "overview_text_1": "To develop a young dynamic team with a creative mind and the right attitude to innovate and provide end-to-end solutions to customers. To transform the current system by providing innovative and path-breaking solutions (to mid-sized firms).",
    "overview_text_2": "To build trust with customers through excellent products and services and ethical practices in all our client interactions.",
    "overview_text_3": "At Roshan Mansoor & Co, we approach each task with commitment and perseverance.  We believe in putting our best foot forward and delivering our best practices in all our endeavours so as to exceed and excel in whatever we do.  We seek to be the Best and provide quality services to all our clients. Our passion to be abreast with the current happenings and technical advancements across industry verticals help us in achieving our mission, vision and Excellence.",
    "overview_text_4": "To broaden our horizons towards growing our team exponentially in different spheres of financial services. And also, forge new business relations and invest equal effort in sustaining this, by truly understanding our clients’ businesses and making genuine efforts to grow them.",
    "overview_text_5": "We uphold high standards of honesty and promise to handle all our client interactions with 100% confidentiality.",
    "overview_text_6": "At Roshan Mansoor & Co, our well-qualified team has an excellent eye for details and we take genuine responsibility to conduct every financial service with due diligence.",
    "overview_text_7": "Our approach towards the financial advice and services is solely based on the book of accounts of the client and unbiased evidence obtained during the course of our service engagement. Further, our work is driven by our ethical practices and the guidelines and framework prescribed by various Authorities nwhich helps us in being objective while dealing with our clients’ business and client engagements.",
    "overview_text_8": "Grow to become one of the best places to work at, with gender neutral and dynamic team of Chartered Accountants.",
    "overview_header_1": "Innovation",
    "overview_header_2": "Trust",
    "overview_header_3": "Excellence",
    "overview_header_4": "Growth",
    "overview_header_5": "Confidentiality",
    "overview_header_6": "Diligence",
    "overview_header_7": "Objectivity",
    "overview_header_8": "Gender Neutral Work Place",
    "meet_pillars": "MEET THE PILLARS OF OUR COMPANY",
    "meet_pillars_text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "pillar_1_name": "Roshan Mansoor",
    "pillar_1_title": "Founder and Managing Partner",
    "pillar_2_name": "Prashant Bansal",
    "pillar_2_title": "Has previously worked for E&Y",
    "pillar_3_name": "Shahid Rokadiya",
    "pillar_3_title": "Partner - Hyderabad",
  },
  "services_index": {
    "auditing": "Auditing & Assurance",
    "auditing_text": "We are committed to serving our clients with the highest possible assurance through our systematic approach. Our relentless endeavor is to deploy newer methods and approaches to enhance the quality of our audit. \n We focus on deciphering comprehensive and pertinent audit findings that not only help streamline but also create a far-reaching impact for our client businesses. We touch upon Internal audit, GST audit, Bank audit, Forensic audit, Statutory and Tax audits.  \n We have so far completed statutory audits of 25+ companies and tax audits of 100+ companies in the last 6 years.",
    "auditing_opt1": "Internal Audit",
    "auditing_opt2": "Statutory Audit",
    "auditing_opt3": "Bank Audit",
    "auditing_opt4": "Forensic Audit",
    "auditing_opt5": "GST Audit",
    "taxation": "TAXATION",
    "taxation_text": "We offer end-to-end solutions for all taxation needs from tax planning, documentation to representations. We have previously represented tax matters from Assessing Officer (Scrutiny) till ITAT level. We have handled cases with respect to search, survey and tax dispute cases. We also help foreign subsidiaries and PE's in India for their remittance certificates and transfer pricing. \n We represent our clients at various offices including that of the Assessing Officer, Appellate Authorities and Tribunal. Our tax planning and assistance services span across personal and corporate entities in terms of acquiring Permanent Account Number (PAN), Tax Deduction Account Number, TDS or withholding taxes, the filing of e-Income tax and e-TDS returns.",
    "taxation_opt1": "Income Tax",
    "taxation_opt2": "GST/VAT",
    "advisory": "ADVISORY",
    "advisory_text": "We provide consultation and advisory services in relation to domestic and international taxation, restructuring and reorganization of companies, acquisitions, and foreign exchange laws.",
    "advisory_opt1": "Due diligence",
    "advisory_opt2": "Mergers & Acquisitions",
    "advisory_opt3": "Corporate Restructuring",
    "advisory_opt4": "FEMA",
    "other_services": "Other Services",
    "other_services_opt1": "Project finance-Debt & Equity",
    "other_services_opt2": "Valuation",
    "other_services_opt3": "Incorporation of entities (Companies/LLP)",
  },
  "services_auditing": {
    "auditing": "AUDITING",
    "main_text1": "We are committed to serving our clients with the highest possible assurance through our systematic approach. Our relentless endeavor is to deploy newer methods and approaches to enhance the quality of our audit.",
    "main_text2": "We focus on deciphering comprehensive and pertinent audit findings that not only help streamline but also create a far-reaching impact for our client businesses. We touch upon Internal audit, GST audit, Bank audit, Forensic audit, Statutory and Tax audits.",
    "main_text3": "We have so far completed statutory audits of 25+ companies and tax audits of 100+ companies in the last 6 years.",
    "paragprah1_header": "Internal Audit",
    "paragprah1_text1": "Our independent, objective assurance and consulting service aim at adding value and improving our clients’ internal operations through realistic approaches that evaluate the effectiveness of risk management, control and governance processes currently deployed in their business.",
    "paragprah1_text2": "Our scalable risk assessment tactics offer an integrated solution that spans across initiating an internal audit function to auditing risk assessments, devising risk-based assurance plans, detecting Key Risk Indicators (KRI) among others.",
    "paragprah2_header": "Statutory Audit",
    "paragprah2_text1": "We undertake a complete and comprehensive review of all your financial records to detect any glitches in terms of accuracy. Our endeavor is to ensure a true representation of our clients’ financial position through our in-depth appraisal of information gathered from sources such as bank balances, bookkeeping records, and financial transactions. Our internal audit reports, verification of financial information, and other documents are in accordance with the specifications of the Government. Our utmost effort is to minimize any possibilities of fraud and create maximum transparency. ",
    "paragprah3_header": "Bank Audit",
    "paragprah3_text1": "Our bank audit service helps you comply with all the statutory requirement. In addition, we also partner with you in getting a bird’s eye view of not only the complete gamut of procedures and services you offer but also the accuracy of all your records. Our review process encompasses examining records such as financial transactions, bank wires, bank account monetary flow among others to ascertain completeness of all your financial activities. ",
    "paragprah4_header": "Foresnic Audit",
    "paragprah4_text1": "We undertake evaluation services of a company’s or individual’s financial information which can be produced as evidence in court. Our multifaceted forensic audit consultancy assists our clients charged with litigations that have high stakes by rendering advisories across independent disputes, assistance in investigations, data acquisition, and analysis.",
    "paragprah5_header": "GST Audit",
    "paragprah5_text1": "Our GST Audit service helps with the company’s GST ( Goods & Service Tax ) registrations, consultation, and audit under GST laws and filling GST returns.",
  },
  "services_advisory": {
    "advisory": "ADVISORY",
    "main_text1": "We provide consultation and advisory services in relation to domestic and international taxation, restructuring and reorganization of companies, acquisitions, and foreign exchange laws.",
    "main_text2": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "paragprah1_header": "Due Diligence",
    "paragprah1_text1": "Our consulting services cover the entire gamut of due diligence activities from both buyer and vendor standpoints. Comprehensive assessment of the deal from commercial, financial, tax and legal standpoints, apart from tax and regulatory issues such as exchange control, income taxes, indirect taxes, and capital market regulations.",
    "paragprah1_text2": "We have undertaken tax due diligence of about 12 companies, the total value of which is approximately USD 48.5 million.",
    "paragprah2_header": "Mergers & Acquisitions",
    "paragprah2_text1": "We help companies with transaction tax advisory services, evaluation of the target and liaising with regulatory bodies and boards for approvals.",
    "paragprah3_header": "Corporate Restructuring",
    "paragprah3_text1": "Our team helps companies to stabilize their operations through financial and operational restructuring. Tailor-made solutions are provided to businesses facing significant liquidity concerns, refinancing risks, deteriorating financial trends, excessive leverage, and management crisis.",
    "paragprah4_header": "Foreign Exchange Management Act ( FEMA )",
    "paragprah4_text1": "We provide Foreign Exchange Management Act Consultation that encompasses the complete gamut of foreign exchange laws.",
  },
  "services_taxation": {
    "taxation": "TAXATION",
    "main_text1": "We offer end-to-end solutions for all taxation needs from tax planning, documentation to representations. We have previously represented tax matters from Assessing Officer (Scrutiny) till ITAT level. We have handled cases with respect to search, survey and tax dispute cases. We also help foreign subsidiaries and PE's in India for their remittance certificates and transfer pricing.",
    "main_text2": "We represent our clients at various offices including that of the Assessing Officer, Appellate Authorities and Tribunal. Our tax planning and assistance services span across personal and corporate entities in terms of acquiring Permanent Account Number (PAN), Tax Deduction Account Number, TDS or withholding taxes, the filing of e-Income tax and e-TDS returns.",
    "paragprah1_header": "Income Tax",
    "paragprah1_text1": "We have filed about 100+ Income tax returns (Individuals, firms, and companies) so far. Our clients for tax preparation service include individuals, firms, Indians stationed overseas, non-Indian nationals, among others.",
    "paragprah2_header": "GST/VAT",
    "paragprah2_text1": "Our all-inclusive consulting takes care of all your GST compliance needs from registrations, returns, to advice. We have Assisted in GST implementation for a manufacturing concern and its subsidiaries from start to end including hand-holding assistance.",
  },
  "other_services": {
    "other_services": "OTHER SERVICES",
    "paragprah1_header": "Project finance-Debt & Equity",
    "paragprah1_text1": "We are proud of our very well-established network in the areas of banking and financial institutions across the country. An edge that will facilitate easier and quicker approvals for all the financing needs.",
    "paragprah1_text2": "Our tailor-made solutions cater to different kinds of financing – from seed funding, venture capital, to private equity funding or debt syndications from Banks/ NBFCs.",
    "paragprah2_header": "Valuation",
    "paragprah2_text1": "Our firm has professionals with valuation experiences in mergers & acquisitions, taxation, and joint-ventures.",
    "paragprah3_header": "Incorporation of entities (Companies/LLP)",
    "paragprah3_text1": "Our team has incorporated about 50+ private companies and 10+ public companies under the Companies Act, 2013. We have also done 20+ LLP incorporation across the country.",
  },
  "auditing_stay_connected": {
    "stay_connected_us": "STAY CONNECTED WITH US",
    "name": "Roshan Mansoor",
    "title": "Managing Partner",
    "list1": "Qualified Chartered Accountant in 2010 and Fellow Chartered Accountant in 2017",
    "list2": "Graduated executive program from IIMB in Private equity & negotiations skills",
    "list3": "Bachelors Degree from JAIN University and Diploma In Finance and Stock Market",
    "list4": "Certification on Mergers and Acquisitions: Wharton University",
    "list5": "Previously Worked for Big 4 Consulting firms like: E&Y and PWC.",
    "list6": "Expertise in Corporate , International Taxation and Mergers & Acquisitions.",
  },
  "industries_index": {
    "information_technology": "Information Technology",
    "information_technology_text": "nformation Technology is the most dynamic industry of today with constant transformations, growth, mergers, and acquisitions. Our expert team caters to this industry by keeping in mind the constantly changing dynamics of the companies operating in this vertical.",
    "retail": "Retail",
    "retail_text": "The retail industry has undergone enormous change after e-Commerce has disrupted the industry as a whole. This has enabled us to introduce robust ERP systems with our clients resulting in more efficient accounting and reliable data for financial and tax planning and better management of cash flows.",
    "real_estate": "Real Estate",
    "real_estate_text": " Engineering and construction companies have a need for on-going audits to ascertain if all the aspects of internal operations meet the standards set by the statutory bodies. We understand this and have dedicated resources catering to the needs of this industry",
    "manufacturing": "Manufacturing",
    "manufacturing_text": "Another highly complex sector, especially from auditing and accounting viewpoint, is Manufacturing. With this sector being a mix of organized and unorganized players, our focus for our manufacturing clients is to device customized solutions for each of the unique issues they come up with.",
    "bio_technology": "Biotechnology",
    "bio_technology_text": "New horizons are emerging from the discoveries and achievements in biotechnology, but the industry is highly volatile and unpredictable sector due to the scientifically intensive operations of companies that reside here. We have undertaken Financial Modeling and Financial Structuring for companies in the biotechnology sector.",
    "media": "Media",
    "media_text": "With high rising consumer demand, the Media industry has a strong growth rate. At Roshan Mansoor & Co, we have provided valuation services for a share acquisition deal for companies in the media sector.",
    "latest_insights_header": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a"
  },
  "industries_information_tech": {
    "information_technology": "INFORMATION TECHNOLOGY",
    "text1": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, writ- ten in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.",
    "text2": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
  },
  "industries_bio_tech": {
    "bio_technology": "BIO TECHNOLOGY",
    "text1": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, writ- ten in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.",
    "text2": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
  },
  "industries_media": {
    "media": "MEDIA",
    "text1": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, writ- ten in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.",
    "text2": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
  },
  "industries_manufacturing": {
    "manufacturing": "Manufacturing",
    "text1": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, writ- ten in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.",
    "text2": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
  },
  "industries_retail": {
    "retail": "Retail",
    "text1": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, writ- ten in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.",
    "text2": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
  },
  "industries_real_estate": {
    "real_estate": "Real Estate Engineering & Construction",
    "text1": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, writ- ten in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.",
    "text2": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
  },
  "industries_key_notes": {
    "key_notes": "KEY NOTES",
    "list1": "Banks and mutual banks",
    "list2": "Investment management funds",
    "list3": "Listed and unlisted real estate investment trusts Insurers",
    "list4": "Providers of products and services to the financial",
    "list5": "services industry.",
  },
  "careers": {
    "careers": "CAREERS",
    "text1": "We are looking for brilliant, passionate people to join us. As a member of our team, we promise you an exciting journey building ground breaking technologies. Even if there is no openings that fits your profile, please reach out to us - we would love to hear from you!",
    "text2": "We are Hiring"
  },
  "contact": {
    "connect": "LETS CONNECT",
    "please_call": "Please call or email contact from and we will be happy to assist you",
    "email_header": "EMAIL",
    "email_adress": "Info@roshanmansoor.com",
    "stay_connected": "STAY CONNECTED WITH US"
  }
}